linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - misspell
    - lll
    - gofumpt
