# ワークフローの名前
name: Go CI

# トリガーになる Github イベント
# PR 作成(pull_request)をトリガーに設定
on:
  pull_request:

# デフォルトの作業ディレクトリ変更
defaults:
  run:
    working-directory: ./backend/app

# ジョブ定義
jobs:
  # ジョブ名
  test:
    # ジョブ実行環境の指定
    runs-on: ubuntu-latest
    # ジョブ内で実行する step を定義
    steps:
      # リポジトリからソースコードの取得
      - uses: actions/checkout@v3
      # Go の実行環境 Set up
      - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.21
      # テストの実行
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: backend/app/...
