# ワークフローの名前
name: golang_ci

# トリガーになる Github イベント
# PR 作成(pull_request)をトリガーに設定
on:
  pull_request:
    branches:
      - develop
    paths:
      - "backend/app/**"
  workflow_dispatch:

# デフォルトの作業ディレクトリ変更
defaults:
  run:
    working-directory: backend/app

# ジョブ定義
jobs:
  # ジョブ名
  go_test:
    # ジョブ実行環境の指定
    runs-on: ubuntu-latest
    # ジョブ内で実行する step を定義
    steps:
      # リポジトリからソースコードの取得
      - name: Checkout Repository
        uses: actions/checkout@v3
      # Go の実行環境 Setup
      - name: Go Setup
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      # テストの実行
      - name: Run Test
        run: go test -v ./... -coverprofile=coverage.out
      - name: Run Octocov
        uses: k1LoW/octocov-action@v0

  go_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Go Setup
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend
