# ワークフローの名前
name: golang_ci

# トリガーになる Github イベント
# PR 作成(pull_request)をトリガーに設定
on:
  pull_request:
    branches:
      - develop
    paths:
      - "backend/**"
  workflow_dispatch:

# ジョブ定義
jobs:
  # ジョブ名
  # shared_steps:
  #   # ジョブ実行環境の指定
  #   runs-on: ubuntu-latest
  #   # ジョブ内で実行する step を定義
  #   steps:
  #     # リポジトリからソースコードの取得
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #       # Go の実行環境 Setup
  #     - name: Go Setup
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: ^1.20

  go_test:
    runs-on: ubuntu-latest
    # needs: shared_steps
    steps:
      # リポジトリからソースコードの取得
      - name: Checkout Repository
        uses: actions/checkout@v3

        # Go の実行環境 Setup
      - name: Go Setup
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      # テストの実行
      - name: Run Test
        run: go test -v ./... -coverprofile=coverage.out
        working-directory: backend

      - name: Run Octocov
        uses: k1LoW/octocov-action@v0

  go_lint:
    runs-on: ubuntu-latest
    # needs: shared_steps
    steps:
      # リポジトリからソースコードの取得
      - name: Checkout Repository
        uses: actions/checkout@v3

        # Go の実行環境 Setup
      - name: Go Setup
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.42.1
          args: --timeout 10m backend/...
