# ワークフローの名前
name: nextjs_ci

# トリガーになる Github イベント
on:
  pull_request:
    branches:
      - develop
    paths:
      - "frontend/**"
  workflow_dispatch:

env:
  DOCKER_IMAGE_TAG: "frontend"

# デフォルトの作業ディレクトリ変更
defaults:
  run:
    working-directory: ./frontend

# ジョブ定義
jobs:
  # ジョブ名
  nextjs_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 使用するNode.jsのバージョンを定義
        node-version: [20.10.0]

    steps:
      # リポジトリからソースコードの取得
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Node.jsのセットアップ
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          # 利用したいNode.jsバージョンを指定
          node-version: ${{ matrix.node-version }}
          # npmのキャッシュを使用する設定
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      # プロジェクトの依存関係をインストール
      - name: Install Dependencies
        run: npm install

      # Prettierでフォーマット
      - name: Format Code
        run: npm run prettier

      # ESlintを実行するnpmスクリプト名に合わせて設定
      - name: Run ESlint Reviewdog
        run: REVIEWDOG_GITHUB_API_TOKEN=$GITHUB_TOKEN npx eslint --format=unix . | npx reviewdog -f=eslint -name="eslint" -reporter=github-pr-check

  nextjs_build_check:
    runs-on: ubuntu-latest
    steps:
      # リポジトリからソースコードの取得
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Dockerのコンテナイメージをビルド
      - name: Docker Image Build
        run: |
          docker build -f Dockerfile -t ${{ env.DOCKER_IMAGE_TAG }} .

      # Dockleで脆弱性検査を行う
      - name: Run Dockle
        uses: erzz/dockle-action@v1
        with:
          image: ${{ env.DOCKER_IMAGE_TAG }}
          exit-code: 1
          failure-threshold: fatal
